from typing import TypedDict, List, Optional

class AgentState(TypedDict):
    """
    Represents the shared memory and state of the multi-agent workflow.
    Every agent reads from and writes to this structure.
    """
    query: str                  # The original user request
    use_web_search: bool        # Flag indicating if live web search is needed
    plan: List[str]             # The step-by-step subtasks generated by the Planner
    research_data: str          # Raw data pulled from live web search
    retrieved_docs: str         # Text chunks retrieved from uploaded PDFs (RAG)
    analysis: str               # The synthesized draft from the Analysis Agent
    critique: str               # Feedback from the Critic Agent (if any)
    draft_approved: bool        # Whether the Critic approved the draft
    final_report: str           # The final formatted markdown report
    revision_count: int         # Tracks how many times the Critic has rejected the draft